### ISSUE TITLE
I am trying to deleteFromCassandra given an rdd containing the primary keys of a table to delete

### ISSUE THREAD

**Issue by k-schmidt** [anguenot/pyspark-cassandra#1]
How hard would this be to implement? I'm not a Java guy but if it's easy enough then I wouldn't mind contributing :). Just need help pointing me in the right direction.

**Comment by anguenot** [comment]
Hey Kyle, 

Please see https://github.com/anguenot/pyspark-cassandra/pull/2 for comments and https://github.com/anguenot/pyspark-cassandra/pull/3 for implementation.

Implementation is currently in a branch. (see PR). 

Let me know if you would like to give it a try using the development version or if you would be interested about a minor release in spark-project.org

   J.
