### ISSUE TITLE
Usage as maven dependency

### ISSUE THREAD

**Issue by ogdabou** [anguenot/pyspark-cassandra#13]
Hi !

**What i'm trying to do**
Add pyspark-cassandra in the pom.xml of Spark 2.2..
meaning running `mvn install` so I've added to the pom :
```
<dependency>
        <groupId>anguenot</groupId>
        <artifactId>pyspark-cassandra</artifactId>
        <version>0.5.0</version>
</dependency>
```

**What I know**
I know that example you provide shows that the package is installed via 
```
spark-submit \
	--packages anguenot/pyspark-cassandra:<version> \
	--conf spark.cassandra.connection.host=your,cassandra,node,names
```
or 
```
spark-submit \
	--jars /path/to/pyspark-cassandra-assembly-<version>.jar \
	--py-files /path/to/pyspark-cassandra-assembly-<version>.jar \
	--conf spark.cassandra.connection.host=your,cassandra,node,names \
	--master spark://spark-master:7077 \
	yourscript.py
```

**The question**

I get the following error : 
```
Failed to execute goal on project POC_Crawler_Worker: Could not resolve dependencies for project fr.blowlitik:POC_Crawler_Worker:jar:1.0-SNAPSHOT: Failure to find anguenot:pyspark-cassandra:jar:0.5.0 in http://maven.cm-cloud.fr/artifactory/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

I just want to understand if the failure is normal or if we missed something.

**Reproduce**
Simply add
```
<dependency>
     <groupId>anguenot</groupId>
     <artifactId>pyspark-cassandra</artifactId>
      <version>0.5.0</version>
</dependency>
```
to any pom.xml you have and try to `mvn install`

Thank you :) !

**Comment by anguenot** [comment]
Hey, 

Try adding the repository below to your pom.xml (or settings.xml) since the package is distributed against spark-packages.org and not maven central.

 ```
<repositories>
  <repository>
    <id>bintray</id>
      <name>bintray</name>
      <url>https://dl.bintray.com/spark-packages/maven</url>
   </repository>
 </repositories>

```
See info here: 

https://mvnrepository.com/artifact/anguenot/pyspark-cassandra/0.5.0 

Let me know if that works on your side. (just tried with an empty pom file and worked just fine for me)

   J.

**Comment by ogdabou** [comment]
Hey ! 

Thanks for your quick answer !
Also sorry I didn't see the link wasn't on mavencentral ..........

Problem solved :).

**Comment by anguenot** [comment]
No problem. Let me know if you got questions and if you need more bindings. Not all Spark Cassandra Connector bindings are exposed yet.
