### ISSUE TITLE
Compatibility with Spark 2.4.5?

### ISSUE THREAD

**Issue by MickeyMouseS** [anguenot/pyspark-cassandra#54]
I am trying to use this package (last version 2.4.0 with Spark 2.4.5 but I get all the time the same error:

Python in worker has different version 2.7 than that in driver 3.7, PySpark cannot run with different minor versions.Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.

Is not compatible yet with 2.4.5 version?

**Comment by anguenot** [comment]
Version 2.4.1 is available and does support up PySpark 2.4.8: https://spark-packages.org/package/anguenot/pyspark-cassandra
